# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\kaos\workspace\ali\Ali1\formularioFinal.ui'
#
# Created: Thu Jan 19 17:10:13 2012
#      by: PyQt4 UI code generator 4.9
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
import Variables
from datetime import date

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_FormularioFinal(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(800, 600)
        Form.setMinimumSize(QtCore.QSize(800, 600))
        Form.setMaximumSize(QtCore.QSize(800, 600))
        self.frame = QtGui.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.frame.setMinimumSize(QtCore.QSize(800, 600))
        self.frame.setStyleSheet(_fromUtf8("QFrame{background-color:#fff9a2;}"))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.tabWidget = QtGui.QTabWidget(self.frame)
        self.tabWidget.setGeometry(QtCore.QRect(20, 50, 761, 431))
        self.tabWidget.setStyleSheet(_fromUtf8("QFrame{background-color:white;}"))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.Detalle = QtGui.QWidget()
        self.Detalle.setAutoFillBackground(False)
        self.Detalle.setObjectName(_fromUtf8("Detalle"))
        self.frame_2 = QtGui.QFrame(self.Detalle)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 761, 411))
        self.frame_2.setStyleSheet(_fromUtf8("QFrame{background-color:white;}"))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.frame_5 = QtGui.QFrame(self.frame_2)
        self.frame_5.setGeometry(QtCore.QRect(30, 270, 261, 101))
        self.frame_5.setStyleSheet(_fromUtf8("QFrame {\n"
"    border: 2px solid black;\n"
"}"))
        self.Calendario = QtGui.QCalendarWidget(self.frame_2)
        self.Calendario.setGeometry(QtCore.QRect(450, 120, 271, 181))
        self.Calendario.setStyleSheet(_fromUtf8(""))
        self.Calendario.setSelectedDate(QtCore.QDate.currentDate())
        self.Calendario.setMinimumDate(QtCore.QDate(2005, 1, 1))
        self.Calendario.setFirstDayOfWeek(QtCore.Qt.Monday)
        self.Calendario.setGridVisible(True)
        self.Calendario.setVerticalHeaderFormat(QtGui.QCalendarWidget.ISOWeekNumbers)
        self.Calendario.setDateEditAcceptDelay(1500)
        self.Calendario.setObjectName(_fromUtf8("Calendario"))
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.textBrowser = QtGui.QTextBrowser(self.frame_5)
        self.textBrowser.setGeometry(QtCore.QRect(0, 0, 261, 101))
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.frame_6 = QtGui.QFrame(self.frame_2)
        self.frame_6.setGeometry(QtCore.QRect(470, 330, 231, 41))
        self.frame_6.setStyleSheet(_fromUtf8("QFrame {\n"
"    border: 2px solid black;\n"
"}"))
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.label_19 = QtGui.QLabel(self.frame_6)
        self.label_19.setGeometry(QtCore.QRect(10, 10, 141, 16))
        self.label_19.setStyleSheet(_fromUtf8("QLabel{border:0px;}"))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.frame_7 = QtGui.QFrame(self.frame_2)
        self.frame_7.setGeometry(QtCore.QRect(30, 40, 411, 201))
        self.frame_7.setStyleSheet(_fromUtf8("QFrame {\n"
"    border: 2px solid black;\n"
"}"))
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.label = QtGui.QLabel(self.frame_7)
        self.label.setGeometry(QtCore.QRect(20, 20, 61, 16))
        self.label.setStyleSheet(_fromUtf8("QLabel{border:0px;}"))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.frame_7)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 61, 16))
        self.label_2.setStyleSheet(_fromUtf8("QLabel{border:0px;}"))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.frame_7)
        self.label_3.setGeometry(QtCore.QRect(20, 100, 81, 16))
        self.label_3.setStyleSheet(_fromUtf8("QLabel{border:0px;}"))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_5 = QtGui.QLabel(self.frame_7)
        self.label_5.setGeometry(QtCore.QRect(20, 140, 71, 16))
        self.label_5.setStyleSheet(_fromUtf8("QLabel{border:0px;}"))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.labelFactura = QtGui.QLabel(self.frame_7)
        self.labelFactura.setGeometry(QtCore.QRect(110, 20, 141, 16))
        self.labelFactura.setStyleSheet(_fromUtf8("QLabel{border:0px;}"))
        self.labelFactura.setObjectName(_fromUtf8("labelFactura"))
        self.labelFecha = QtGui.QLabel(self.frame_7)
        self.labelFecha.setGeometry(QtCore.QRect(110, 60, 141, 16))
        self.labelFecha.setStyleSheet(_fromUtf8("QLabel{border:0px;}"))
        self.labelFecha.setObjectName(_fromUtf8("labelFecha"))
        self.labelNombre = QtGui.QLabel(self.frame_7)
        self.labelNombre.setGeometry(QtCore.QRect(110, 100, 131, 16))
        self.labelNombre.setStyleSheet(_fromUtf8("QLabel{border:0px;}"))
        self.labelNombre.setObjectName(_fromUtf8("labelNombre"))
        self.labelNumero = QtGui.QLabel(self.frame_7)
        self.labelNumero.setGeometry(QtCore.QRect(110, 140, 141, 16))
        self.labelNumero.setStyleSheet(_fromUtf8("QLabel{border:0px;}"))
        self.labelNumero.setObjectName(_fromUtf8("labelNumero"))
        self.label_4 = QtGui.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(30, 20, 46, 13))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.frame_8 = QtGui.QFrame(self.frame_2)
        self.frame_8.setGeometry(QtCore.QRect(490, 40, 231, 80))
        self.frame_8.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_8.setObjectName(_fromUtf8("frame_8"))
        self.frame_8.setStyleSheet(_fromUtf8("QFrame {\n"
"    background-image:url(../iconos/logo1.png);\n background-repeat: no-repeat;"

"}"))
        self.label_6 = QtGui.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(30, 250, 81, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(470, 310, 46, 13))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.tabWidget.addTab(self.Detalle, _fromUtf8(""))
        self.Lista = QtGui.QWidget()
        self.Lista.setObjectName(_fromUtf8("Lista"))
        self.frame_4 = QtGui.QFrame(self.Lista)
        self.frame_4.setGeometry(QtCore.QRect(0, 0, 761, 411))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.tableWidget = QtGui.QTableWidget(self.frame_4)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 761, 411))
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.tabWidget.addTab(self.Lista, _fromUtf8(""))
        self.Cliente = QtGui.QWidget()
        self.Cliente.setObjectName(_fromUtf8("Cliente"))
        self.frame_3 = QtGui.QFrame(self.Cliente)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 761, 411))
        self.frame_3.setStyleSheet(_fromUtf8("QFrame{background-color:white;}"))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.frame_9 = QtGui.QFrame(self.frame_3)
        self.frame_9.setGeometry(QtCore.QRect(420, 120, 321, 111))
        self.frame_9.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_9.setObjectName(_fromUtf8("frame_9"))
        self.frame_9.setStyleSheet(_fromUtf8("QFrame {\n"
"    background-image:url(../iconos/logo1.png);\n background-repeat: no-repeat;"

"}"))
        self.frame_10 = QtGui.QFrame(self.frame_3)
        self.frame_10.setGeometry(QtCore.QRect(30, 30, 371, 321))
        self.frame_10.setStyleSheet(_fromUtf8("QFrame {\n"
"    border: 2px solid black;\n"
"}"))
        self.frame_10.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_10.setObjectName(_fromUtf8("frame_10"))
        self.label_8 = QtGui.QLabel(self.frame_10)
        self.label_8.setGeometry(QtCore.QRect(20, 20, 61, 16))
        self.label_8.setStyleSheet(_fromUtf8("QLabel{border:0px;}"))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.frame_10)
        self.label_9.setGeometry(QtCore.QRect(20, 60, 61, 16))
        self.label_9.setStyleSheet(_fromUtf8("QLabel{border:0px;}"))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.frame_10)
        self.label_10.setGeometry(QtCore.QRect(20, 100, 81, 16))
        self.label_10.setStyleSheet(_fromUtf8("QLabel{border:0px;}"))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_18 = QtGui.QLabel(self.frame_10)
        self.label_18.setGeometry(QtCore.QRect(20, 140, 71, 16))
        self.label_18.setStyleSheet(_fromUtf8("QLabel{border:0px;}"))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.labelNumeroCliente = QtGui.QLabel(self.frame_10)
        self.labelNumeroCliente.setGeometry(QtCore.QRect(110, 20, 141, 16))
        self.labelNumeroCliente.setStyleSheet(_fromUtf8("QLabel{border:0px;}"))
        self.labelNumeroCliente.setObjectName(_fromUtf8("labelNumeroCliente"))
        self.labelNombreCliente = QtGui.QLabel(self.frame_10)
        self.labelNombreCliente.setGeometry(QtCore.QRect(110, 60, 141, 16))
        self.labelNombreCliente.setStyleSheet(_fromUtf8("QLabel{border:0px;}"))
        self.labelNombreCliente.setObjectName(_fromUtf8("labelNombreCliente"))
        self.labelDireccion = QtGui.QLabel(self.frame_10)
        self.labelDireccion.setGeometry(QtCore.QRect(110, 100, 131, 16))
        self.labelDireccion.setStyleSheet(_fromUtf8("QLabel{border:0px;}"))
        self.labelDireccion.setObjectName(_fromUtf8("labelDireccion"))
        self.labelDNI = QtGui.QLabel(self.frame_10)
        self.labelDNI.setGeometry(QtCore.QRect(110, 140, 141, 16))
        self.labelDNI.setStyleSheet(_fromUtf8("QLabel{border:0px;}"))
        self.labelDNI.setObjectName(_fromUtf8("labelDNI"))
        self.label_20 = QtGui.QLabel(self.frame_10)
        self.label_20.setGeometry(QtCore.QRect(20, 180, 71, 16))
        self.label_20.setStyleSheet(_fromUtf8("QLabel{border:0px;}"))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.labelCiudad = QtGui.QLabel(self.frame_10)
        self.labelCiudad.setGeometry(QtCore.QRect(110, 180, 141, 16))
        self.labelCiudad.setStyleSheet(_fromUtf8("QLabel{border:0px;}"))
        self.labelCiudad.setObjectName(_fromUtf8("labelCiudad"))
        self.label_21 = QtGui.QLabel(self.frame_10)
        self.label_21.setGeometry(QtCore.QRect(20, 220, 71, 16))
        self.label_21.setStyleSheet(_fromUtf8("QLabel{border:0px;}"))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.labelPais = QtGui.QLabel(self.frame_10)
        self.labelPais.setGeometry(QtCore.QRect(110, 220, 141, 16))
        self.labelPais.setStyleSheet(_fromUtf8("QLabel{border:0px;}"))
        self.labelPais.setObjectName(_fromUtf8("labelPais"))
        self.label_22 = QtGui.QLabel(self.frame_10)
        self.label_22.setGeometry(QtCore.QRect(20, 260, 71, 16))
        self.label_22.setStyleSheet(_fromUtf8("QLabel{border:0px;}"))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.labelCP = QtGui.QLabel(self.frame_10)
        self.labelCP.setGeometry(QtCore.QRect(110, 260, 141, 16))
        self.labelCP.setStyleSheet(_fromUtf8("QLabel{border:0px;}"))
        self.labelCP.setObjectName(_fromUtf8("labelCP"))
        self.tabWidget.addTab(self.Cliente, _fromUtf8(""))
        self.buttonBorrar = QtGui.QPushButton(self.frame)
        self.buttonBorrar.setGeometry(QtCore.QRect(650, 20, 81, 31))
        self.buttonBorrar.setObjectName(_fromUtf8("buttonBorrar"))
        self.buttonVolver = QtGui.QPushButton(self.frame)
        self.buttonVolver.setGeometry(QtCore.QRect(20, 510, 81, 31))
        self.buttonVolver.setObjectName(_fromUtf8("buttonVolver"))
        self.buttonImprimir = QtGui.QPushButton(self.frame)
        self.buttonImprimir.setGeometry(QtCore.QRect(340, 510, 81, 31))
        self.buttonImprimir.setObjectName(_fromUtf8("buttonImprimir"))
        self.pushButton_4 = QtGui.QPushButton(self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(680, 510, 81, 31))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))

        total=0
        i=0
        #imprimimos lineas
        for linea in Variables.Variables.factura.lista:
            self.tableWidget.insertRow(i)
            self.tableWidget.setItem(i,0,QtGui.QTableWidgetItem(str(linea.albaran)))
            self.tableWidget.item(i,0).setFlags( QtCore.Qt.ItemIsSelectable |  QtCore.Qt.ItemIsEnabled)
            self.tableWidget.setItem(i,1,QtGui.QTableWidgetItem(str(linea.nombre)))
            self.tableWidget.item(i,1).setFlags( QtCore.Qt.ItemIsSelectable |  QtCore.Qt.ItemIsEnabled)
            self.tableWidget.setItem(i,2,QtGui.QTableWidgetItem(str(linea.cantidad)))
            self.tableWidget.item(i,2).setFlags( QtCore.Qt.ItemIsSelectable |  QtCore.Qt.ItemIsEnabled)
            self.tableWidget.setItem(i,3,QtGui.QTableWidgetItem(str(linea.precio)))
            self.tableWidget.item(i,3).setFlags( QtCore.Qt.ItemIsSelectable |  QtCore.Qt.ItemIsEnabled)
            self.tableWidget.setItem(i,4,QtGui.QTableWidgetItem(str(linea.descuento)+" %"))
            self.tableWidget.item(i,4).setFlags( QtCore.Qt.ItemIsSelectable |  QtCore.Qt.ItemIsEnabled)
            self.tableWidget.setItem(i,5,QtGui.QTableWidgetItem(str((linea.cantidad*linea.precio)*((100-linea.descuento))/100)))
            self.tableWidget.item(i,5).setFlags( QtCore.Qt.ItemIsSelectable |  QtCore.Qt.ItemIsEnabled)
            total=total+float(self.tableWidget.item(i,5).text())
            i=i+1

        self.retranslateUi(Form)
        self.labelCiudad.setText(str(Variables.Variables.cliente.ciudad))
        self.labelPais.setText(str(Variables.Variables.cliente.pais))
        self.labelCP.setText(str(Variables.Variables.cliente.CP))
        self.labelDireccion.setText(str(Variables.Variables.cliente.direccion))
        self.labelDNI.setText(str(Variables.Variables.cliente.cif))
        self.labelFactura.setText(str(Variables.Variables.factura.idFactura))
        #imprimimos la fecha
        if(Variables.Variables.factura.idFactura==""):
            dia=date.today()
            self.labelFecha.setText(dia.strftime("%d-%m-%Y"))
        else:
            self.labelFecha.setText(Variables.Variables.factura.fecha.strftime("%d-%m-%Y"))
            
        self.labelNombre.setText(str(Variables.Variables.cliente.nombre))
        self.labelNombreCliente.setText(str(Variables.Variables.cliente.nombre))
        self.textBrowser.setText(str(Variables.Variables.factura.observaciones))
        self.labelNumero.setText(str(len(Variables.Variables.factura.lista))) 
        self.labelNumeroCliente.setText(str(Variables.Variables.cliente.idCliente))
        self.label_19.setText(str(total) + " Euros")
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBorrar, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.lazarBorrarFactura)
        QtCore.QObject.connect(self.buttonVolver, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.lazarCancelar)
        QtCore.QObject.connect(self.buttonImprimir, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.lazarImprimir)
        QtCore.QObject.connect(self.pushButton_4, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.lazarAceptar)
        QtCore.QObject.connect(self.Calendario,QtCore.SIGNAL(_fromUtf8("selectionChanged ()")),Form.lazarCambiarFecha)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Form", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Nº Factura", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Fecha", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Nombre Cliente", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "Nº Productos", None, QtGui.QApplication.UnicodeUTF8))
        self.labelFactura.setText(QtGui.QApplication.translate("Form", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.labelFecha.setText(QtGui.QApplication.translate("Form", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.labelNombre.setText(QtGui.QApplication.translate("Form", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.labelNumero.setText(QtGui.QApplication.translate("Form", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "Detalle", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "Observaciones", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form", "Total", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Detalle), QtGui.QApplication.translate("Form", "Detalle", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("Form", "albaran", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("Form", "producto", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("Form", "cantidad", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("Form", "precio", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("Form", "descuento", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(QtGui.QApplication.translate("Form", "subtotal", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Lista), QtGui.QApplication.translate("Form", "Lista", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Form", "Nº Cliente", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Form", "Nombre", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Form", "Direccion", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Form", "DNI/CIF", None, QtGui.QApplication.UnicodeUTF8))
        self.labelNumeroCliente.setText(QtGui.QApplication.translate("Form", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.labelNombreCliente.setText(QtGui.QApplication.translate("Form", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.labelDireccion.setText(QtGui.QApplication.translate("Form", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.labelDNI.setText(QtGui.QApplication.translate("Form", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("Form", "Ciudad", None, QtGui.QApplication.UnicodeUTF8))
        self.labelCiudad.setText(QtGui.QApplication.translate("Form", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("Form", "Pais", None, QtGui.QApplication.UnicodeUTF8))
        self.labelPais.setText(QtGui.QApplication.translate("Form", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("Form", "Codigo Postal", None, QtGui.QApplication.UnicodeUTF8))
        self.labelCP.setText(QtGui.QApplication.translate("Form", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Cliente), QtGui.QApplication.translate("Form", "Cliente", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonBorrar.setText(QtGui.QApplication.translate("Form", "Borrar", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonVolver.setText(QtGui.QApplication.translate("Form", "Volver", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonImprimir.setText(QtGui.QApplication.translate("Form", "Aceptar e \n"
" Imprimir", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setText(QtGui.QApplication.translate("Form", "Aceptar", None, QtGui.QApplication.UnicodeUTF8))

